// <auto-generated />
using System;
using CodeFirst8.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeFirst8.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20231108211558_11m")]
    partial class _11m
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeFirst8.Models.Autor", b =>
                {
                    b.Property<int>("id_autor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_autor"));

                    b.Property<int>("id_libro")
                        .HasColumnType("integer");

                    b.HasKey("id_autor");

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("CodeFirst8.Models.Libro", b =>
                {
                    b.Property<int>("id_libro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_libro"));

                    b.Property<int>("id_autor")
                        .HasColumnType("integer");

                    b.Property<int>("id_prestamo")
                        .HasColumnType("integer");

                    b.HasKey("id_libro");

                    b.ToTable("Libro");
                });

            modelBuilder.Entity("CodeFirst8.Models.Prestamo", b =>
                {
                    b.Property<int>("id_prestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_prestamo"));

                    b.Property<int>("id_libro")
                        .HasColumnType("integer");

                    b.HasKey("id_prestamo");

                    b.ToTable("Prestamo");
                });

            modelBuilder.Entity("Rel_Autores_Libros", b =>
                {
                    b.Property<int>("id_libro")
                        .HasColumnType("integer");

                    b.Property<int>("id_autor")
                        .HasColumnType("integer");

                    b.HasKey("id_libro", "id_autor");

                    b.HasIndex("id_autor");

                    b.ToTable("Rel_Autores_Libros");
                });

            modelBuilder.Entity("Rel_Libros_Prestamos", b =>
                {
                    b.Property<int>("Libros_Prestamosid_libro")
                        .HasColumnType("integer");

                    b.Property<int>("Prestamos_Librosid_prestamo")
                        .HasColumnType("integer");

                    b.Property<int?>("id_libro")
                        .HasColumnType("integer");

                    b.HasKey("Libros_Prestamosid_libro", "Prestamos_Librosid_prestamo");

                    b.HasIndex("Prestamos_Librosid_prestamo");

                    b.HasIndex("id_libro");

                    b.ToTable("Rel_Libros_Prestamos");
                });

            modelBuilder.Entity("Rel_Autores_Libros", b =>
                {
                    b.HasOne("CodeFirst8.Models.Autor", null)
                        .WithMany()
                        .HasForeignKey("id_autor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirst8.Models.Libro", null)
                        .WithMany()
                        .HasForeignKey("id_libro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rel_Libros_Prestamos", b =>
                {
                    b.HasOne("CodeFirst8.Models.Libro", null)
                        .WithMany()
                        .HasForeignKey("Libros_Prestamosid_libro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirst8.Models.Prestamo", null)
                        .WithMany()
                        .HasForeignKey("Prestamos_Librosid_prestamo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirst8.Models.Libro", null)
                        .WithMany()
                        .HasForeignKey("id_libro");
                });
#pragma warning restore 612, 618
        }
    }
}
