// <auto-generated />
using System;
using CodeFirst8.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeFirst8.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20231109130021_19m")]
    partial class _19m
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeFirst8.Models.Acceso", b =>
                {
                    b.Property<int>("id_acceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_acceso"));

                    b.Property<string>("codigo_acceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descripcion_acceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_acceso");

                    b.ToTable("Accesos");
                });

            modelBuilder.Entity("CodeFirst8.Models.Autor", b =>
                {
                    b.Property<int>("id_autor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_autor"));

                    b.Property<string>("codigo_acceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descripcion_acceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_autor");

                    b.ToTable("Autores");
                });

            modelBuilder.Entity("CodeFirst8.Models.Coleccion", b =>
                {
                    b.Property<int>("id_coleccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_coleccion"));

                    b.Property<string>("nombre_coleccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_coleccion");

                    b.ToTable("Colecciones");
                });

            modelBuilder.Entity("CodeFirst8.Models.Editorial", b =>
                {
                    b.Property<int>("id_editorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_editorial"));

                    b.Property<string>("nombre_editorial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_editorial");

                    b.ToTable("Editoriales");
                });

            modelBuilder.Entity("CodeFirst8.Models.EstadoPrestamo", b =>
                {
                    b.Property<int>("id_estado_prestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_estado_prestamo"));

                    b.Property<string>("codigo_estado_prestamo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("descripcion_estado_prestamo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_estado_prestamo");

                    b.ToTable("Estados_Prestamos");
                });

            modelBuilder.Entity("CodeFirst8.Models.Genero", b =>
                {
                    b.Property<int>("id_genero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_genero"));

                    b.Property<string>("descripcion_genero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre_genero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_genero");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("CodeFirst8.Models.Libro", b =>
                {
                    b.Property<int>("id_libro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_libro"));

                    b.Property<string>("edicion_libro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_coleccion")
                        .HasColumnType("integer");

                    b.Property<int>("id_editorial")
                        .HasColumnType("integer");

                    b.Property<int>("id_genero")
                        .HasColumnType("integer");

                    b.Property<string>("isbn_libro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("titulo_libro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_libro");

                    b.HasIndex("id_coleccion");

                    b.HasIndex("id_editorial");

                    b.HasIndex("id_genero");

                    b.ToTable("Libros");
                });

            modelBuilder.Entity("CodeFirst8.Models.Prestamo", b =>
                {
                    b.Property<int>("id_prestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_prestamo"));

                    b.Property<int>("cantidad_libro")
                        .HasColumnType("integer");

                    b.Property<DateTime>("fch_entrega_prestamo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fch_fin_prestamo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fch_inicio_prestamo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("id_estdo_prestamo")
                        .HasColumnType("integer");

                    b.Property<int>("id_usuario")
                        .HasColumnType("integer");

                    b.HasKey("id_prestamo");

                    b.HasIndex("id_estdo_prestamo");

                    b.HasIndex("id_usuario");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("CodeFirst8.Models.Usuario", b =>
                {
                    b.Property<int>("id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_usuario"));

                    b.Property<string>("apellidos_usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("clave_usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("dni_usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("email_usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("estaBloqueado_usuario")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("fch_alta_usuario")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fch_baja_usuario")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("fch_fin_bloqueo_usuario")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("id_acceso")
                        .HasColumnType("integer");

                    b.Property<string>("nombre_usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tlf_usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_usuario");

                    b.HasIndex("id_acceso");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Rel_Autores_Libros", b =>
                {
                    b.Property<int>("id_libro")
                        .HasColumnType("integer");

                    b.Property<int>("id_autor")
                        .HasColumnType("integer");

                    b.HasKey("id_libro", "id_autor");

                    b.HasIndex("id_autor");

                    b.ToTable("Rel_Autores_Libros");
                });

            modelBuilder.Entity("Rel_Prestamos_Libros", b =>
                {
                    b.Property<int>("id_libro")
                        .HasColumnType("integer");

                    b.Property<int>("id_prestamo")
                        .HasColumnType("integer");

                    b.HasKey("id_libro", "id_prestamo");

                    b.HasIndex("id_prestamo");

                    b.ToTable("Rel_Prestamos_Libros");
                });

            modelBuilder.Entity("CodeFirst8.Models.Libro", b =>
                {
                    b.HasOne("CodeFirst8.Models.Coleccion", "coleccion")
                        .WithMany("LibrosColeccion")
                        .HasForeignKey("id_coleccion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirst8.Models.Editorial", "editorial")
                        .WithMany("LibrosEditorial")
                        .HasForeignKey("id_editorial")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirst8.Models.Genero", "genero")
                        .WithMany("LibrosGenero")
                        .HasForeignKey("id_genero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("coleccion");

                    b.Navigation("editorial");

                    b.Navigation("genero");
                });

            modelBuilder.Entity("CodeFirst8.Models.Prestamo", b =>
                {
                    b.HasOne("CodeFirst8.Models.EstadoPrestamo", "estado")
                        .WithMany("PrestamoEstado")
                        .HasForeignKey("id_estdo_prestamo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirst8.Models.Usuario", "usuario")
                        .WithMany("PrestamoUsuario")
                        .HasForeignKey("id_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("estado");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("CodeFirst8.Models.Usuario", b =>
                {
                    b.HasOne("CodeFirst8.Models.Acceso", "acceso")
                        .WithMany("UsuarioAcceso")
                        .HasForeignKey("id_acceso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("acceso");
                });

            modelBuilder.Entity("Rel_Autores_Libros", b =>
                {
                    b.HasOne("CodeFirst8.Models.Autor", null)
                        .WithMany()
                        .HasForeignKey("id_autor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirst8.Models.Libro", null)
                        .WithMany()
                        .HasForeignKey("id_libro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Rel_Prestamos_Libros", b =>
                {
                    b.HasOne("CodeFirst8.Models.Libro", null)
                        .WithMany()
                        .HasForeignKey("id_libro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirst8.Models.Prestamo", null)
                        .WithMany()
                        .HasForeignKey("id_prestamo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeFirst8.Models.Acceso", b =>
                {
                    b.Navigation("UsuarioAcceso");
                });

            modelBuilder.Entity("CodeFirst8.Models.Coleccion", b =>
                {
                    b.Navigation("LibrosColeccion");
                });

            modelBuilder.Entity("CodeFirst8.Models.Editorial", b =>
                {
                    b.Navigation("LibrosEditorial");
                });

            modelBuilder.Entity("CodeFirst8.Models.EstadoPrestamo", b =>
                {
                    b.Navigation("PrestamoEstado");
                });

            modelBuilder.Entity("CodeFirst8.Models.Genero", b =>
                {
                    b.Navigation("LibrosGenero");
                });

            modelBuilder.Entity("CodeFirst8.Models.Usuario", b =>
                {
                    b.Navigation("PrestamoUsuario");
                });
#pragma warning restore 612, 618
        }
    }
}
